server:
  port: 18080    #端口号设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: test1      #服务名称.在注册中心你将看到对应的注册名



feign:
  httpclient:
    connection-timeout: 5000   #设置超时时间
  hystrix:
    enabled: true               #开启熔断器
    command:
      default:
        execution:
          isolation:
            semaphore:
              maxConcurrentRequests: 200

  # datasource:
  #   username: root
  #   password: root
  #   url: jdbc:mysql:///db5
  #   driver-class-name: com.mysql.jdbc.Driver